### ISSUE TITLE
Does "Color Table Size" specify the number of bytes, or entries?

### ISSUE THREAD

**Issue by generalmimon** [gfcwfzkm/PIF-Image-Format#4]
I suspect it should be the number of bytes, since the "important" resources seem to prefer this semantics, but it's not 100% clear because some files quite explicitly suggest otherwise:

## Number of bytes:

- [test_images/Lenna/**Lenna_Indexed16_RGB565.pif**](https://github.com/gfcwfzkm/PIF-Image-Format/blob/74775a60cc8d4e634f3ab916446e82e55f53921b/test_images/Lenna/Lenna_Indexed16_RGB565.pif) (`ColorTableSize` is 32, which matches the number of bytes)
- https://github.com/gfcwfzkm/PIF-Image-Format/blob/74775a60cc8d4e634f3ab916446e82e55f53921b/Image%20Converter/PIFGUI.py#L772-L779
- https://github.com/gfcwfzkm/PIF-Image-Format/blob/b0cee7fcd4a2f84d47bd214663b08d762178d20c/Image%20Viewer/PIF%20Viewer/Viewer.cs#L123-L137
- https://github.com/WerWolv/ImHex-Patterns/blob/3edc6ea17270d9befef95d634d1f0318a9c8d4a7/patterns/pif.hexpat#L46-L57

## Number of entries:

- [Specification/**PIF Format Specification.pdf**](https://github.com/gfcwfzkm/PIF-Image-Format/blob/74775a60cc8d4e634f3ab916446e82e55f53921b/Specification/PIF%20Format%20Specification.pdf)

  > Color Table Size: **Index size** of the color table, only used in Indexed mode, otherwise zero.

  To me, "index size" suggests the number of entries, not bytes. I understand "index size" as the size of the index set, i.e. "the maximum color table index that a pixel can refer to" plus 1 (because indices are from 0 to the number of color table entries minus one).

- https://github.com/gfcwfzkm/PIF-Image-Format/blob/74775a60cc8d4e634f3ab916446e82e55f53921b/C%20Library/pifdec.h#L68

  ```c
  typedef struct {
        // ...
  	uint16_t colTableSize;		// Color Table Size in Entries
        // ...
  }pifINFO_t;
  ```

  I know that just because there's some field in `pifINFO_t` doesn't mean the actual file format uses the same semantics (for example see `imageType`, which has different values in `pifINFO_t` than the file format uses). But in this case, `colTableSize` is copied verbatim from the input **.pif** file without any conversion:

  https://github.com/gfcwfzkm/PIF-Image-Format/blob/74775a60cc8d4e634f3ab916446e82e55f53921b/C%20Library/pifdec.c#L359

  And later in the code it's indeed treated as a number of entries (so it's not a lying code comment):

  https://github.com/gfcwfzkm/PIF-Image-Format/blob/74775a60cc8d4e634f3ab916446e82e55f53921b/C%20Library/pifdec.c#L421-L425

**Comment by gfcwfzkm** [comment]
Misclick.

Anyways, I agree there that using different keywords or treating the same keywords between implementations and the documentation is not a good thing there. I'll take a closer look soon into it and change the code implementations accordingly. Thanks!

**Comment by gfcwfzkm** [comment]
I've finally took a closer look to it and compared all implementations against eachother an the documentation. The correct term, for 'Color Table Size' is the number of bytes that the table holds.
The documentation has been changed to state it better, together with a note to state it more clearly. On top of that, it seemed like the C implementation had a bug, which has been fixed now.

The documentation has been changed to state the following on the first page:
> Note: While ColorTableSize states the amount of bytes in the ColorTable, the ImageType states how many bytes make up a color.
On the second page, the details regarding the Color Table Size state now:
> Size of the color table in bytes, only used in Indexed mode, otherwise zero.

What do you think, is it more clear now?
Thanks in advance!

**Comment by generalmimon** [comment]
> What do you think, is it more clear now?

Yes, now it looks great. Thank you for addressing this issue.
